/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controller.Paciente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.PacienteAcess;

/**
 *
 * @author Mateus Couto
 */
public class form_paciente extends javax.swing.JFrame {

  public form_paciente() {
    initComponents();
    preencherTable();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jT_nome = new javax.swing.JTextField();
    jF_cpf = new javax.swing.JFormattedTextField();
    jF_data = new javax.swing.JFormattedTextField();
    jT_email = new javax.swing.JTextField();
    jF_telefone = new javax.swing.JFormattedTextField();
    jC_sexo = new javax.swing.JComboBox<>();
    jButton1 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jC_tipoMedico = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jT_tabelapaciente = new javax.swing.JTable();
    jPanel4 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));

    jPanel1.setForeground(new java.awt.Color(102, 102, 102));

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setText("Nome");

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    jLabel5.setText("Cpf");

    jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("Email");

    jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(0, 0, 0));
    jLabel7.setText("Telefone");

    jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(0, 0, 0));
    jLabel8.setText("Data de Nascimento");

    jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(0, 0, 0));
    jLabel9.setText("Sexo");

    try {
      jF_cpf.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(
          new javax.swing.text.MaskFormatter("###.###.###.##")
        )
      );
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      jF_data.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(
          new javax.swing.text.MaskFormatter("##/##/####")
        )
      );
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      jF_telefone.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(
          new javax.swing.text.MaskFormatter("(##)#####-####")
        )
      );
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    jC_sexo.setModel(
      new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Masculino", "Feminino" }
      )
    );
    jC_sexo.setSelectedIndex(-1);
    jC_sexo.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jC_sexoActionPerformed(evt);
        }
      }
    );

    jButton1.setText("Salvar");
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jButton4.setText("Limpar");
    jButton4.addActionListener(
      new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton4ActionPerformed(evt);
        }
      }
    );

    jC_tipoMedico.setModel(
      new javax.swing.DefaultComboBoxModel<>(
        new String[] {
          "Cardiologista",
          "Dermatologista",
          "Ginecologista",
          "Ortopedista",
          "Urologista",
          "Oftalmologista",
          "Oncologista",
          "Pediatra",
          "Neurologista",
        }
      )
    );
    jC_tipoMedico.setSelectedIndex(-1);

    jLabel1.setBackground(new java.awt.Color(51, 51, 51));
    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setText("Médico");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addGroup(
                              jPanel1Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                            )
                            .addGap(18, 18, 18)
                            .addGroup(
                              jPanel1Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addGroup(
                                  jPanel1Layout
                                    .createSequentialGroup()
                                    .addComponent(
                                      jF_cpf,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      120,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                    .addGap(0, 0, Short.MAX_VALUE)
                                )
                                .addComponent(jT_nome)
                            )
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addGroup(
                              jPanel1Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addGroup(
                                  jPanel1Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                      jF_telefone,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      106,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                                .addGroup(
                                  jPanel1Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                      jT_email,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      240,
                                      javax.swing.GroupLayout.PREFERRED_SIZE
                                    )
                                )
                            )
                            .addGap(0, 18, Short.MAX_VALUE)
                        )
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      82,
                      Short.MAX_VALUE
                    )
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(
                      jButton1,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      111,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
            )
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel1Layout
                    .createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      jC_tipoMedico,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      125,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGap(152, 152, 152)
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(
                              jF_data,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              88,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addGroup(
                              jPanel1Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  false
                                )
                                .addComponent(
                                  jButton4,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  Short.MAX_VALUE
                                )
                                .addComponent(jC_sexo, 0, 109, Short.MAX_VALUE)
                            )
                        )
                    )
                    .addGap(90, 90, 90)
                )
            )
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(
                  jT_nome,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(41, 41, 41)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(jLabel5)
                        .addComponent(
                          jF_cpf,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(47, 47, 47)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(jLabel6)
                        .addComponent(
                          jT_email,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(52, 52, 52)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel1Layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE
                            )
                            .addComponent(jLabel9)
                            .addComponent(
                              jC_sexo,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          jPanel1Layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.BASELINE
                            )
                            .addComponent(jLabel7)
                            .addComponent(
                              jF_telefone,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              28,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                    )
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(jLabel8)
                        .addComponent(
                          jF_data,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(59, 59, 59)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.BASELINE
                        )
                        .addComponent(
                          jC_tipoMedico,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(jLabel1)
                    )
                )
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              52,
              Short.MAX_VALUE
            )
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jButton1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  37,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jButton4,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  37,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(27, 27, 27)
        )
    );

    jTabbedPane1.addTab("Cadastro", jPanel1);

    jT_tabelapaciente.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {
          { null, null, null, null, null, null, null, null },
          { null, null, null, null, null, null, null, null },
          { null, null, null, null, null, null, null, null },
          { null, null, null, null, null, null, null, null },
        },
        new String[] {
          "id",
          "nome",
          "cpf",
          "email",
          "sexo",
          "d.nascimento",
          "telefone",
          "tipo médico",
        }
      ) {
        boolean[] canEdit = new boolean[] {
          false,
          true,
          false,
          false,
          false,
          false,
          true,
          false,
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
          return canEdit[columnIndex];
        }
      }
    );
    jScrollPane1.setViewportView(jT_tabelapaciente);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              749,
              Short.MAX_VALUE
            )
        )
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              367,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(10, Short.MAX_VALUE)
        )
    );

    jTabbedPane1.addTab("Lista de Pascientes", jPanel2);

    jPanel4.setBackground(new java.awt.Color(68, 137, 254));

    jLabel10.setBackground(new java.awt.Color(255, 255, 255));
    jLabel10.setFont(new java.awt.Font("Yu Gothic Light", 2, 60)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setText("Unijorge Clinic ");

    jLabel11.setBackground(new java.awt.Color(255, 255, 255));
    jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 2, 36)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setText("Cadastro de Pacientes e Listagem ");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
      jPanel4
    );
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel4Layout
            .createSequentialGroup()
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(jLabel11)
            .addGap(22, 22, 22)
        )
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(jLabel10)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGap(56, 56, 56)
            .addComponent(
              jLabel10,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              91,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel11)
            .addContainerGap(12, Short.MAX_VALUE)
        )
    );

    jButton3.setText("jButton3");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel4,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
        .addComponent(jTabbedPane1)
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addComponent(
              jPanel4,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              jTabbedPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              409,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jC_sexoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jC_sexoActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_jC_sexoActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
    jT_nome.setText("");
    jF_cpf.setText("");
    jT_email.setText("");
    jF_data.setText("");
    jF_telefone.setText("");
    jC_sexo.setSelectedIndex(-1);
    jC_tipoMedico.setSelectedIndex(-1);
  } //GEN-LAST:event_jButton4ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    Paciente p = new Paciente();
    p.setNome(jT_nome.getText());
    p.setCpf(jF_cpf.getText());
    p.setEmail(jT_email.getText());
    p.setNascimento(jF_data.getText());
    p.setTelefone(jF_telefone.getText());
    p.setSexo(jC_sexo.getSelectedItem().toString());
    p.setTipo_medico(jC_tipoMedico.getSelectedItem().toString());
    PacienteAcess pAcess = new PacienteAcess();
    pAcess.register(p);
    preencherTable();
    jTabbedPane1.setSelectedIndex(1);
  } //GEN-LAST:event_jButton1ActionPerformed

  public void preencherTable() {
    PacienteAcess pAcess = new PacienteAcess();
    List<Paciente> lista = pAcess.listarTodos();
    DefaultTableModel modeloTabela = (DefaultTableModel) jT_tabelapaciente.getModel();
    modeloTabela.setRowCount(0);
    for (Paciente p : lista) {
      modeloTabela.addRow(
        new Object[] {
          p.getId_paciente(),
          p.getNome(),
          p.getCpf(),
          p.getEmail(),
          p.getSexo(),
          p.getNascimento(),
          p.getTelefone(),
          p.getTipo_medico(),
        }
      );
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java
        .util.logging.Logger.getLogger(form_paciente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java
        .util.logging.Logger.getLogger(form_paciente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java
        .util.logging.Logger.getLogger(form_paciente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java
        .util.logging.Logger.getLogger(form_paciente.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {

        public void run() {
          new form_paciente().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JComboBox<String> jC_sexo;
  private javax.swing.JComboBox<String> jC_tipoMedico;
  private javax.swing.JFormattedTextField jF_cpf;
  private javax.swing.JFormattedTextField jF_data;
  private javax.swing.JFormattedTextField jF_telefone;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jT_email;
  private javax.swing.JTextField jT_nome;
  private javax.swing.JTable jT_tabelapaciente;
  private javax.swing.JTabbedPane jTabbedPane1;
  // End of variables declaration//GEN-END:variables
}
